<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Overview of the incidence package • incidence</title>
<!-- jquery --><script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha384-nrOSfDHtoPMzJHjVTdCopGqIqeYETSXhZDFyniQ8ZHcVy08QesyHcnOUpMpqnmWq" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script><!-- Font Awesome icons --><link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.7.1/clipboard.min.js" integrity="sha384-cV+rhyOuRHc9Ub/91rihWcGmMmCXDeksTtCihMupQHSsi8GIIRDG0ThDc3HGQFJ3" crossorigin="anonymous"></script><!-- sticky kit --><script src="https://cdnjs.cloudflare.com/ajax/libs/sticky-kit/1.1.3/sticky-kit.min.js" integrity="sha256-c4Rlo1ZozqTPE2RLuvbusY3+SU1pQaJC0TjuhygMipw=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Overview of the incidence package">
<meta property="og:description" content="">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">incidence</a>
        <span class="label label-default" data-toggle="tooltip" data-placement="bottom" title="Released package">1.4.1.99</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fa fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/conversions.html">Conversions to and from the incidence class</a>
    </li>
    <li>
      <a href="../articles/customize_plot.html">Customize plots of incidence</a>
    </li>
    <li>
      <a href="../articles/incidence_class.html">Details of the incidence class</a>
    </li>
    <li>
      <a href="../articles/incidence_fit_class.html">Details of the incidence_fit class</a>
    </li>
    <li>
      <a href="../articles/overview.html">Overview of the incidence package</a>
    </li>
  </ul>
</li>
<li>
  <a href="../news/index.html">Changelog</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right"></ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      
      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>Overview of the incidence package</h1>
                        <h4 class="author">Thibaut Jombart</h4>
            
            <h4 class="date">2018-10-30</h4>
      
      
      <div class="hidden name"><code>overview.Rmd</code></div>

    </div>

    
    
<p><em>incidence</em> implements functions and classes to compute, handle, visualise and model incidences from dates data. This vignette provides an overview of current features. It largely reproduces the content of <code>REAME.md</code>.</p>
<p><br></p>
<div id="installing-the-package" class="section level1">
<h1 class="hasAnchor">
<a href="#installing-the-package" class="anchor"></a>Installing the package</h1>
<p>To install the current stable, CRAN version of the package, type:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" data-line-number="1"><span class="kw">install.packages</span>(<span class="st">"incidence"</span>)</a></code></pre></div>
<p>To benefit from the latest features and bug fixes, install the development, <em>github</em> version of the package using:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb2-1" data-line-number="1">devtools<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/devtools/topics/reexports">install_github</a></span>(<span class="st">"reconhub/incidence"</span>)</a></code></pre></div>
<p>Note that this requires the package <em>devtools</em> installed.</p>
<p><br></p>
</div>
<div id="what-does-it-do" class="section level1">
<h1 class="hasAnchor">
<a href="#what-does-it-do" class="anchor"></a>What does it do?</h1>
<p>The main functions of the package include:</p>
<ul>
<li><p><strong><code>incidence</code></strong>: compute incidence from dates in various formats; any fixed time interval can be used; the returned object is an instance of the (S3) class <em>incidence</em>.</p></li>
<li><p><strong><code>plot</code></strong>: this method (see <code><a href="../reference/plot.incidence.html">?plot.incidence</a></code> for details) plots <em>incidence</em> objects, and can also add predictions of the model(s) contained in an <em>incidence_fit</em> object (or a list of such objects).</p></li>
<li><p><strong><code>fit</code></strong>: fit one or two exponential models (i.e. linear regression on log-incidence) to an <em>incidence</em> object; two models are calibrated only if a date is provided to split the time series in two (argument <code>split</code>); this is typically useful to model the two phases of exponential growth, and decrease of an outbreak; each model returned is an instance of the (S3) class <em>incidence_fit</em>, each of which contains various useful information (e.g. growth rate <em>r</em>, doubling/halving time, predictions and confidence intervals); results can be plotted using <code>plot</code>, or added to an existing <code>uncudence</code> plot using the piping-friendly function <code>add_incidence_fit</code>.</p></li>
<li><p><strong><code>fit_optim_split</code></strong>: finds the optimal date to split the time series in two, typically around the peak of the epidemic.</p></li>
<li><p><strong><code>[</code></strong>: lower-level subsetting of <em>incidence</em> objects, permiting to specify which dates and groups to retain; uses a syntax similar to matrices, i.e. <code>x[i, j]</code>, where <code>x</code> is the <em>incidence</em> object, <code>i</code> a subset of dates, and <code>j</code> a subset of groups.</p></li>
<li><p><strong><code>subset</code></strong>: subset an <em>incidence</em> object by specifying a time window.</p></li>
<li><p><strong><code>pool</code></strong>: pool incidence from different groups into one global incidence time series.</p></li>
<li><p><strong><code>cumulate</code></strong>: computes cumulative incidence over time from and <code>incidence</code> object.</p></li>
<li><p><strong><code>as.data.frame</code></strong>: converts an <em>incidence</em> object into a <code>data.frame</code> containing dates and incidence values.</p></li>
<li><p><strong><code>bootstrap</code></strong>: generates a bootstrapped <em>incidence</em> object by re-sampling, with replacement, the original dates of events.</p></li>
<li><p><strong><code>find_peak</code></strong>: locates the peak time of the epicurve.</p></li>
<li><p><strong><code>estimate_peak</code></strong>: uses bootstrap to estimate the peak time (and related confidence interval) of a partially observed outbreak.</p></li>
</ul>
<p><br></p>
</div>
<div id="worked-example-simulated-ebola-outbreak" class="section level1">
<h1 class="hasAnchor">
<a href="#worked-example-simulated-ebola-outbreak" class="anchor"></a>Worked example: simulated Ebola outbreak</h1>
<div id="loading-the-data" class="section level2">
<h2 class="hasAnchor">
<a href="#loading-the-data" class="anchor"></a>Loading the data</h2>
<p>This example uses the simulated Ebola Virus Disease (EVD) outbreak from the package <a href="http://github.com/reconhub/outbreaks"><em>outbreaks</em></a>. We will compute incidence for various time steps, calibrate two exponential models around the peak of the epidemic, and analyse the results.</p>
<p>First, we load the data:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" data-line-number="1"><span class="kw">library</span>(outbreaks)</a>
<a class="sourceLine" id="cb3-2" data-line-number="2"><span class="kw">library</span>(ggplot2)</a>
<a class="sourceLine" id="cb3-3" data-line-number="3"><span class="kw">library</span>(incidence)</a>
<a class="sourceLine" id="cb3-4" data-line-number="4"></a>
<a class="sourceLine" id="cb3-5" data-line-number="5">dat &lt;-<span class="st"> </span>ebola_sim<span class="op">$</span>linelist<span class="op">$</span>date_of_onset</a>
<a class="sourceLine" id="cb3-6" data-line-number="6"><span class="kw">class</span>(dat)</a>
<a class="sourceLine" id="cb3-7" data-line-number="7"><span class="co">#&gt; [1] "Date"</span></a>
<a class="sourceLine" id="cb3-8" data-line-number="8"><span class="kw">head</span>(dat)</a>
<a class="sourceLine" id="cb3-9" data-line-number="9"><span class="co">#&gt; [1] "2014-04-07" "2014-04-15" "2014-04-21" "2014-04-27" "2014-04-26"</span></a>
<a class="sourceLine" id="cb3-10" data-line-number="10"><span class="co">#&gt; [6] "2014-04-25"</span></a></code></pre></div>
</div>
<div id="computing-and-plotting-incidence" class="section level2">
<h2 class="hasAnchor">
<a href="#computing-and-plotting-incidence" class="anchor"></a>Computing and plotting incidence</h2>
<p>We compute the daily incidence:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" data-line-number="1">i &lt;-<span class="st"> </span><span class="kw"><a href="../reference/incidence.html">incidence</a></span>(dat)</a>
<a class="sourceLine" id="cb4-2" data-line-number="2">i</a>
<a class="sourceLine" id="cb4-3" data-line-number="3"><span class="co">#&gt; &lt;incidence object&gt;</span></a>
<a class="sourceLine" id="cb4-4" data-line-number="4"><span class="co">#&gt; [5888 cases from days 2014-04-07 to 2015-04-30]</span></a>
<a class="sourceLine" id="cb4-5" data-line-number="5"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb4-6" data-line-number="6"><span class="co">#&gt; $counts: matrix with 389 rows and 1 columns</span></a>
<a class="sourceLine" id="cb4-7" data-line-number="7"><span class="co">#&gt; $n: 5888 cases in total</span></a>
<a class="sourceLine" id="cb4-8" data-line-number="8"><span class="co">#&gt; $dates: 389 dates marking the left-side of bins</span></a>
<a class="sourceLine" id="cb4-9" data-line-number="9"><span class="co">#&gt; $interval: 1 day</span></a>
<a class="sourceLine" id="cb4-10" data-line-number="10"><span class="co">#&gt; $timespan: 389 days</span></a>
<a class="sourceLine" id="cb4-11" data-line-number="11"><span class="co">#&gt; $cumulative: FALSE</span></a>
<a class="sourceLine" id="cb4-12" data-line-number="12"><span class="kw">plot</span>(i)</a></code></pre></div>
<p><img src="overview_files/figure-html/incid1-1.png" width="672"></p>
<p>The daily incidence is quite noisy, but we can easily compute other incidence using larger time intervals:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" data-line-number="1"><span class="co">## weekly</span></a>
<a class="sourceLine" id="cb5-2" data-line-number="2">i<span class="fl">.7</span> &lt;-<span class="st"> </span><span class="kw"><a href="../reference/incidence.html">incidence</a></span>(dat, <span class="dt">interval=</span><span class="dv">7</span>)</a>
<a class="sourceLine" id="cb5-3" data-line-number="3"><span class="kw">plot</span>(i<span class="fl">.7</span>)</a></code></pre></div>
<p><img src="overview_files/figure-html/interv-1.png" width="672"></p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb6-1" data-line-number="1"></a>
<a class="sourceLine" id="cb6-2" data-line-number="2"><span class="co">## bi-weekly</span></a>
<a class="sourceLine" id="cb6-3" data-line-number="3">i<span class="fl">.14</span> &lt;-<span class="st"> </span><span class="kw"><a href="../reference/incidence.html">incidence</a></span>(dat, <span class="dt">interval=</span><span class="dv">14</span>)</a>
<a class="sourceLine" id="cb6-4" data-line-number="4"><span class="kw">plot</span>(i<span class="fl">.14</span>, <span class="dt">border =</span> <span class="st">"white"</span>)</a></code></pre></div>
<p><img src="overview_files/figure-html/interv-2.png" width="672"></p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" data-line-number="1"></a>
<a class="sourceLine" id="cb7-2" data-line-number="2"><span class="co">## monthly</span></a>
<a class="sourceLine" id="cb7-3" data-line-number="3">i.month &lt;-<span class="st"> </span><span class="kw"><a href="../reference/incidence.html">incidence</a></span>(dat, <span class="dt">interval=</span><span class="st">"month"</span>)</a>
<a class="sourceLine" id="cb7-4" data-line-number="4"><span class="kw">plot</span>(i.month, <span class="dt">border =</span> <span class="st">"white"</span>)</a></code></pre></div>
<p><img src="overview_files/figure-html/interv-3.png" width="672"></p>
<p><code>incidence</code> can also compute incidence by specified groups using the <code>groups</code> argument. For instance, we can compute incidence by gender:</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" data-line-number="1">i.<span class="fl">7.</span>sex &lt;-<span class="st"> </span><span class="kw"><a href="../reference/incidence.html">incidence</a></span>(dat, <span class="dt">interval =</span> <span class="dv">7</span>, <span class="dt">groups =</span> ebola_sim<span class="op">$</span>linelist<span class="op">$</span>gender)</a>
<a class="sourceLine" id="cb8-2" data-line-number="2">i.<span class="fl">7.</span>sex</a>
<a class="sourceLine" id="cb8-3" data-line-number="3"><span class="co">#&gt; &lt;incidence object&gt;</span></a>
<a class="sourceLine" id="cb8-4" data-line-number="4"><span class="co">#&gt; [5888 cases from days 2014-04-07 to 2015-04-27]</span></a>
<a class="sourceLine" id="cb8-5" data-line-number="5"><span class="co">#&gt; [5888 cases from ISO weeks 2014-W15 to 2015-W18]</span></a>
<a class="sourceLine" id="cb8-6" data-line-number="6"><span class="co">#&gt; [2 groups: f, m]</span></a>
<a class="sourceLine" id="cb8-7" data-line-number="7"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb8-8" data-line-number="8"><span class="co">#&gt; $counts: matrix with 56 rows and 2 columns</span></a>
<a class="sourceLine" id="cb8-9" data-line-number="9"><span class="co">#&gt; $n: 5888 cases in total</span></a>
<a class="sourceLine" id="cb8-10" data-line-number="10"><span class="co">#&gt; $dates: 56 dates marking the left-side of bins</span></a>
<a class="sourceLine" id="cb8-11" data-line-number="11"><span class="co">#&gt; $interval: 7 days</span></a>
<a class="sourceLine" id="cb8-12" data-line-number="12"><span class="co">#&gt; $timespan: 386 days</span></a>
<a class="sourceLine" id="cb8-13" data-line-number="13"><span class="co">#&gt; $cumulative: FALSE</span></a>
<a class="sourceLine" id="cb8-14" data-line-number="14"><span class="kw">plot</span>(i.<span class="fl">7.</span>sex, <span class="dt">stack =</span> <span class="ot">TRUE</span>, <span class="dt">border =</span> <span class="st">"grey"</span>)</a></code></pre></div>
<p><img src="overview_files/figure-html/gender-1.png" width="672"></p>
<p>We can do the same for hospitals, using the ‘clean’ version of the dataset, with some customization of the legend:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" data-line-number="1">i.<span class="fl">7.</span>hosp &lt;-<span class="st"> </span><span class="kw">with</span>(ebola_sim_clean<span class="op">$</span>linelist, </a>
<a class="sourceLine" id="cb9-2" data-line-number="2">     <span class="kw"><a href="../reference/incidence.html">incidence</a></span>(date_of_onset, <span class="dt">interval=</span><span class="dv">7</span>, <span class="dt">groups =</span> hospital))</a>
<a class="sourceLine" id="cb9-3" data-line-number="3">i.<span class="fl">7.</span>hosp</a>
<a class="sourceLine" id="cb9-4" data-line-number="4"><span class="co">#&gt; &lt;incidence object&gt;</span></a>
<a class="sourceLine" id="cb9-5" data-line-number="5"><span class="co">#&gt; [5829 cases from days 2014-04-07 to 2015-04-27]</span></a>
<a class="sourceLine" id="cb9-6" data-line-number="6"><span class="co">#&gt; [5829 cases from ISO weeks 2014-W15 to 2015-W18]</span></a>
<a class="sourceLine" id="cb9-7" data-line-number="7"><span class="co">#&gt; [6 groups: Connaught Hospital, Military Hospital, NA, other, Princess Christian Maternity Hospital (PCMH), Rokupa Hospital]</span></a>
<a class="sourceLine" id="cb9-8" data-line-number="8"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb9-9" data-line-number="9"><span class="co">#&gt; $counts: matrix with 56 rows and 6 columns</span></a>
<a class="sourceLine" id="cb9-10" data-line-number="10"><span class="co">#&gt; $n: 5829 cases in total</span></a>
<a class="sourceLine" id="cb9-11" data-line-number="11"><span class="co">#&gt; $dates: 56 dates marking the left-side of bins</span></a>
<a class="sourceLine" id="cb9-12" data-line-number="12"><span class="co">#&gt; $interval: 7 days</span></a>
<a class="sourceLine" id="cb9-13" data-line-number="13"><span class="co">#&gt; $timespan: 386 days</span></a>
<a class="sourceLine" id="cb9-14" data-line-number="14"><span class="co">#&gt; $cumulative: FALSE</span></a>
<a class="sourceLine" id="cb9-15" data-line-number="15"><span class="kw">head</span>(i.<span class="fl">7.</span>hosp<span class="op">$</span>counts)</a>
<a class="sourceLine" id="cb9-16" data-line-number="16"><span class="co">#&gt;      Connaught Hospital Military Hospital NA other</span></a>
<a class="sourceLine" id="cb9-17" data-line-number="17"><span class="co">#&gt; [1,]                  0                 1  0     0</span></a>
<a class="sourceLine" id="cb9-18" data-line-number="18"><span class="co">#&gt; [2,]                  1                 0  0     0</span></a>
<a class="sourceLine" id="cb9-19" data-line-number="19"><span class="co">#&gt; [3,]                  0                 0  2     3</span></a>
<a class="sourceLine" id="cb9-20" data-line-number="20"><span class="co">#&gt; [4,]                  1                 0  1     0</span></a>
<a class="sourceLine" id="cb9-21" data-line-number="21"><span class="co">#&gt; [5,]                  3                 5  1     1</span></a>
<a class="sourceLine" id="cb9-22" data-line-number="22"><span class="co">#&gt; [6,]                  2                 4  4     5</span></a>
<a class="sourceLine" id="cb9-23" data-line-number="23"><span class="co">#&gt;      Princess Christian Maternity Hospital (PCMH) Rokupa Hospital</span></a>
<a class="sourceLine" id="cb9-24" data-line-number="24"><span class="co">#&gt; [1,]                                            0               0</span></a>
<a class="sourceLine" id="cb9-25" data-line-number="25"><span class="co">#&gt; [2,]                                            0               0</span></a>
<a class="sourceLine" id="cb9-26" data-line-number="26"><span class="co">#&gt; [3,]                                            0               0</span></a>
<a class="sourceLine" id="cb9-27" data-line-number="27"><span class="co">#&gt; [4,]                                            1               1</span></a>
<a class="sourceLine" id="cb9-28" data-line-number="28"><span class="co">#&gt; [5,]                                            1               1</span></a>
<a class="sourceLine" id="cb9-29" data-line-number="29"><span class="co">#&gt; [6,]                                            1               1</span></a>
<a class="sourceLine" id="cb9-30" data-line-number="30"><span class="kw">plot</span>(i.<span class="fl">7.</span>hosp, <span class="dt">stack=</span><span class="ot">TRUE</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb9-31" data-line-number="31"><span class="st">    </span><span class="kw"><a href="ggplot2.tidyverse.org/reference/theme.html">theme</a></span>(<span class="dt">legend.position=</span> <span class="st">"top"</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb9-32" data-line-number="32"><span class="st">    </span><span class="kw"><a href="ggplot2.tidyverse.org/reference/labs.html">labs</a></span>(<span class="dt">fill=</span><span class="st">""</span>)</a></code></pre></div>
<p><img src="overview_files/figure-html/hosp-1.png" width="672"></p>
</div>
<div id="handling-incidence-objects" class="section level2">
<h2 class="hasAnchor">
<a href="#handling-incidence-objects" class="anchor"></a>Handling <code>incidence</code> objects</h2>
<p><code>incidence</code> objects can be manipulated easily. The <code>[</code> operator implements subetting of dates (first argument) and groups (second argument). For instance, to keep only the peak of the distribution:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb10-1" data-line-number="1">i[<span class="dv">100</span><span class="op">:</span><span class="dv">250</span>]</a>
<a class="sourceLine" id="cb10-2" data-line-number="2"><span class="co">#&gt; &lt;incidence object&gt;</span></a>
<a class="sourceLine" id="cb10-3" data-line-number="3"><span class="co">#&gt; [4103 cases from days 2014-07-15 to 2014-12-12]</span></a>
<a class="sourceLine" id="cb10-4" data-line-number="4"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb10-5" data-line-number="5"><span class="co">#&gt; $counts: matrix with 151 rows and 1 columns</span></a>
<a class="sourceLine" id="cb10-6" data-line-number="6"><span class="co">#&gt; $n: 4103 cases in total</span></a>
<a class="sourceLine" id="cb10-7" data-line-number="7"><span class="co">#&gt; $dates: 151 dates marking the left-side of bins</span></a>
<a class="sourceLine" id="cb10-8" data-line-number="8"><span class="co">#&gt; $interval: 1 day</span></a>
<a class="sourceLine" id="cb10-9" data-line-number="9"><span class="co">#&gt; $timespan: 151 days</span></a>
<a class="sourceLine" id="cb10-10" data-line-number="10"><span class="co">#&gt; $cumulative: FALSE</span></a>
<a class="sourceLine" id="cb10-11" data-line-number="11"><span class="kw">plot</span>(i[<span class="dv">100</span><span class="op">:</span><span class="dv">250</span>])</a></code></pre></div>
<p><img src="overview_files/figure-html/middle-1.png" width="672"></p>
<p>Or to keep every other week:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" data-line-number="1">i<span class="fl">.7</span>[<span class="kw">c</span>(<span class="ot">TRUE</span>,<span class="ot">FALSE</span>)]</a>
<a class="sourceLine" id="cb11-2" data-line-number="2"><span class="co">#&gt; &lt;incidence object&gt;</span></a>
<a class="sourceLine" id="cb11-3" data-line-number="3"><span class="co">#&gt; [2891 cases from days 2014-04-07 to 2015-04-20]</span></a>
<a class="sourceLine" id="cb11-4" data-line-number="4"><span class="co">#&gt; [2891 cases from ISO weeks 2014-W15 to 2015-W17]</span></a>
<a class="sourceLine" id="cb11-5" data-line-number="5"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb11-6" data-line-number="6"><span class="co">#&gt; $counts: matrix with 28 rows and 1 columns</span></a>
<a class="sourceLine" id="cb11-7" data-line-number="7"><span class="co">#&gt; $n: 2891 cases in total</span></a>
<a class="sourceLine" id="cb11-8" data-line-number="8"><span class="co">#&gt; $dates: 28 dates marking the left-side of bins</span></a>
<a class="sourceLine" id="cb11-9" data-line-number="9"><span class="co">#&gt; $interval: 7 days</span></a>
<a class="sourceLine" id="cb11-10" data-line-number="10"><span class="co">#&gt; $timespan: 379 days</span></a>
<a class="sourceLine" id="cb11-11" data-line-number="11"><span class="co">#&gt; $cumulative: FALSE</span></a>
<a class="sourceLine" id="cb11-12" data-line-number="12"><span class="kw">plot</span>(i<span class="fl">.7</span>[<span class="kw">c</span>(<span class="ot">TRUE</span>,<span class="ot">FALSE</span>)])</a></code></pre></div>
<p><img src="overview_files/figure-html/stripes-1.png" width="672"></p>
<p>Some temporal subsetting can be even simpler using <code>subset</code>, which permits to retain data within a specified time window:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb12-1" data-line-number="1">i.tail &lt;-<span class="st"> </span><span class="kw">subset</span>(i, <span class="dt">from=</span><span class="kw">as.Date</span>(<span class="st">"2015-01-01"</span>))</a>
<a class="sourceLine" id="cb12-2" data-line-number="2">i.tail</a>
<a class="sourceLine" id="cb12-3" data-line-number="3"><span class="co">#&gt; &lt;incidence object&gt;</span></a>
<a class="sourceLine" id="cb12-4" data-line-number="4"><span class="co">#&gt; [1205 cases from days 2015-01-01 to 2015-04-30]</span></a>
<a class="sourceLine" id="cb12-5" data-line-number="5"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb12-6" data-line-number="6"><span class="co">#&gt; $counts: matrix with 120 rows and 1 columns</span></a>
<a class="sourceLine" id="cb12-7" data-line-number="7"><span class="co">#&gt; $n: 1205 cases in total</span></a>
<a class="sourceLine" id="cb12-8" data-line-number="8"><span class="co">#&gt; $dates: 120 dates marking the left-side of bins</span></a>
<a class="sourceLine" id="cb12-9" data-line-number="9"><span class="co">#&gt; $interval: 1 day</span></a>
<a class="sourceLine" id="cb12-10" data-line-number="10"><span class="co">#&gt; $timespan: 120 days</span></a>
<a class="sourceLine" id="cb12-11" data-line-number="11"><span class="co">#&gt; $cumulative: FALSE</span></a>
<a class="sourceLine" id="cb12-12" data-line-number="12"><span class="kw">plot</span>(i.tail, <span class="dt">border=</span><span class="st">"white"</span>)</a></code></pre></div>
<p><img src="overview_files/figure-html/tail-1.png" width="672"></p>
<p>Subsetting groups can also matter. For instance, let’s try and visualise the incidence based on onset of symptoms by outcome:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" data-line-number="1">i.<span class="fl">7.</span>outcome &lt;-<span class="st"> </span><span class="kw"><a href="../reference/incidence.html">incidence</a></span>(dat, <span class="dv">7</span>, <span class="dt">groups=</span>ebola_sim<span class="op">$</span>linelist<span class="op">$</span>outcome)</a>
<a class="sourceLine" id="cb13-2" data-line-number="2">i.<span class="fl">7.</span>outcome</a>
<a class="sourceLine" id="cb13-3" data-line-number="3"><span class="co">#&gt; &lt;incidence object&gt;</span></a>
<a class="sourceLine" id="cb13-4" data-line-number="4"><span class="co">#&gt; [5888 cases from days 2014-04-07 to 2015-04-27]</span></a>
<a class="sourceLine" id="cb13-5" data-line-number="5"><span class="co">#&gt; [5888 cases from ISO weeks 2014-W15 to 2015-W18]</span></a>
<a class="sourceLine" id="cb13-6" data-line-number="6"><span class="co">#&gt; [3 groups: Death, NA, Recover]</span></a>
<a class="sourceLine" id="cb13-7" data-line-number="7"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb13-8" data-line-number="8"><span class="co">#&gt; $counts: matrix with 56 rows and 3 columns</span></a>
<a class="sourceLine" id="cb13-9" data-line-number="9"><span class="co">#&gt; $n: 5888 cases in total</span></a>
<a class="sourceLine" id="cb13-10" data-line-number="10"><span class="co">#&gt; $dates: 56 dates marking the left-side of bins</span></a>
<a class="sourceLine" id="cb13-11" data-line-number="11"><span class="co">#&gt; $interval: 7 days</span></a>
<a class="sourceLine" id="cb13-12" data-line-number="12"><span class="co">#&gt; $timespan: 386 days</span></a>
<a class="sourceLine" id="cb13-13" data-line-number="13"><span class="co">#&gt; $cumulative: FALSE</span></a>
<a class="sourceLine" id="cb13-14" data-line-number="14"><span class="kw">plot</span>(i.<span class="fl">7.</span>outcome, <span class="dt">stack =</span> <span class="ot">TRUE</span>, <span class="dt">border =</span> <span class="st">"grey"</span>)</a></code></pre></div>
<p><img src="overview_files/figure-html/i7outcome-1.png" width="672"></p>
<p>By default, <code>incidence</code> treats missing data (NA) as a separate group (see argument <code>na_as_group</code>). We could disable this to retain only known outcomes, but alternatively we can simply subset the object to exclude the last (3rd) group:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb14-1" data-line-number="1">i.<span class="fl">7.</span>outcome[,<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>]</a>
<a class="sourceLine" id="cb14-2" data-line-number="2"><span class="co">#&gt; &lt;incidence object&gt;</span></a>
<a class="sourceLine" id="cb14-3" data-line-number="3"><span class="co">#&gt; [3905 cases from days 2014-04-07 to 2015-04-27]</span></a>
<a class="sourceLine" id="cb14-4" data-line-number="4"><span class="co">#&gt; [3905 cases from ISO weeks 2014-W15 to 2015-W18]</span></a>
<a class="sourceLine" id="cb14-5" data-line-number="5"><span class="co">#&gt; [2 groups: Death, NA]</span></a>
<a class="sourceLine" id="cb14-6" data-line-number="6"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb14-7" data-line-number="7"><span class="co">#&gt; $counts: matrix with 56 rows and 2 columns</span></a>
<a class="sourceLine" id="cb14-8" data-line-number="8"><span class="co">#&gt; $n: 3905 cases in total</span></a>
<a class="sourceLine" id="cb14-9" data-line-number="9"><span class="co">#&gt; $dates: 56 dates marking the left-side of bins</span></a>
<a class="sourceLine" id="cb14-10" data-line-number="10"><span class="co">#&gt; $interval: 7 days</span></a>
<a class="sourceLine" id="cb14-11" data-line-number="11"><span class="co">#&gt; $timespan: 386 days</span></a>
<a class="sourceLine" id="cb14-12" data-line-number="12"><span class="co">#&gt; $cumulative: FALSE</span></a>
<a class="sourceLine" id="cb14-13" data-line-number="13"><span class="kw">plot</span>(i.<span class="fl">7.</span>outcome[,<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>], <span class="dt">stack =</span> <span class="ot">TRUE</span>, <span class="dt">border =</span> <span class="st">"grey"</span>)</a></code></pre></div>
<p><img src="overview_files/figure-html/groupsub-1.png" width="672"></p>
<p>Groups can also be collapsed into a single time series using <code>pool</code>:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" data-line-number="1">i.pooled &lt;-<span class="st"> </span><span class="kw"><a href="../reference/pool.html">pool</a></span>(i.<span class="fl">7.</span>outcome)</a>
<a class="sourceLine" id="cb15-2" data-line-number="2">i.pooled</a>
<a class="sourceLine" id="cb15-3" data-line-number="3"><span class="co">#&gt; &lt;incidence object&gt;</span></a>
<a class="sourceLine" id="cb15-4" data-line-number="4"><span class="co">#&gt; [5888 cases from days 2014-04-07 to 2015-04-27]</span></a>
<a class="sourceLine" id="cb15-5" data-line-number="5"><span class="co">#&gt; [5888 cases from ISO weeks 2014-W15 to 2015-W18]</span></a>
<a class="sourceLine" id="cb15-6" data-line-number="6"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb15-7" data-line-number="7"><span class="co">#&gt; $counts: matrix with 56 rows and 1 columns</span></a>
<a class="sourceLine" id="cb15-8" data-line-number="8"><span class="co">#&gt; $n: 5888 cases in total</span></a>
<a class="sourceLine" id="cb15-9" data-line-number="9"><span class="co">#&gt; $dates: 56 dates marking the left-side of bins</span></a>
<a class="sourceLine" id="cb15-10" data-line-number="10"><span class="co">#&gt; $interval: 7 days</span></a>
<a class="sourceLine" id="cb15-11" data-line-number="11"><span class="co">#&gt; $timespan: 386 days</span></a>
<a class="sourceLine" id="cb15-12" data-line-number="12"><span class="co">#&gt; $cumulative: FALSE</span></a>
<a class="sourceLine" id="cb15-13" data-line-number="13"><span class="kw">identical</span>(i<span class="fl">.7</span><span class="op">$</span>counts, i.pooled<span class="op">$</span>counts)</a>
<a class="sourceLine" id="cb15-14" data-line-number="14"><span class="co">#&gt; [1] TRUE</span></a></code></pre></div>
</div>
<div id="modelling-incidence" class="section level2">
<h2 class="hasAnchor">
<a href="#modelling-incidence" class="anchor"></a>Modelling incidence</h2>
<p>Incidence data, excluding zeros, can be modelled using log-linear regression of the form: log(<em>y</em>) = <em>r</em> x <em>t</em> + <em>b</em></p>
<p>where <em>y</em> is the incidence, <em>r</em> is the growth rate, <em>t</em> is the number of days since a specific point in time (typically the start of the outbreak), and <em>b</em> is the intercept.</p>
<p>Such model can be fitted to any incidence object using <code>fit</code>. Of course, a single log-linear model is not sufficient for modelling our epidemic curve, as there is clearly an growing and a decreasing phase. As a start, we can calibrate a model on the first 20 weeks of the epidemic:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb16-1" data-line-number="1"><span class="kw">plot</span>(i<span class="fl">.7</span>[<span class="dv">1</span><span class="op">:</span><span class="dv">20</span>])</a></code></pre></div>
<p><img src="overview_files/figure-html/fit1-1.png" width="672"></p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" data-line-number="1">early.fit &lt;-<span class="st"> </span><span class="kw"><a href="../reference/fit.html">fit</a></span>(i<span class="fl">.7</span>[<span class="dv">1</span><span class="op">:</span><span class="dv">20</span>])</a>
<a class="sourceLine" id="cb17-2" data-line-number="2">early.fit</a>
<a class="sourceLine" id="cb17-3" data-line-number="3"><span class="co">#&gt; &lt;incidence_fit object&gt;</span></a>
<a class="sourceLine" id="cb17-4" data-line-number="4"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb17-5" data-line-number="5"><span class="co">#&gt; $model: regression of log-incidence over time</span></a>
<a class="sourceLine" id="cb17-6" data-line-number="6"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb17-7" data-line-number="7"><span class="co">#&gt; $info: list containing the following items:</span></a>
<a class="sourceLine" id="cb17-8" data-line-number="8"><span class="co">#&gt;   $r (daily growth rate):</span></a>
<a class="sourceLine" id="cb17-9" data-line-number="9"><span class="co">#&gt; [1] 0.03175771</span></a>
<a class="sourceLine" id="cb17-10" data-line-number="10"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb17-11" data-line-number="11"><span class="co">#&gt;   $r.conf (confidence interval):</span></a>
<a class="sourceLine" id="cb17-12" data-line-number="12"><span class="co">#&gt;           2.5 %     97.5 %</span></a>
<a class="sourceLine" id="cb17-13" data-line-number="13"><span class="co">#&gt; [1,] 0.02596229 0.03755314</span></a>
<a class="sourceLine" id="cb17-14" data-line-number="14"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb17-15" data-line-number="15"><span class="co">#&gt;   $doubling (doubling time in days):</span></a>
<a class="sourceLine" id="cb17-16" data-line-number="16"><span class="co">#&gt; [1] 21.8261</span></a>
<a class="sourceLine" id="cb17-17" data-line-number="17"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb17-18" data-line-number="18"><span class="co">#&gt;   $doubling.conf (confidence interval):</span></a>
<a class="sourceLine" id="cb17-19" data-line-number="19"><span class="co">#&gt;         2.5 %   97.5 %</span></a>
<a class="sourceLine" id="cb17-20" data-line-number="20"><span class="co">#&gt; [1,] 18.45777 26.69823</span></a>
<a class="sourceLine" id="cb17-21" data-line-number="21"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb17-22" data-line-number="22"><span class="co">#&gt;   $pred: data.frame of incidence predictions (20 rows, 5 columns)</span></a></code></pre></div>
<p>The resulting objects (known as <code>incidence_fit</code> objects) can be plotted, in which case the prediction and its confidence interval is displayed:</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb18-1" data-line-number="1"><span class="kw">plot</span>(early.fit)</a></code></pre></div>
<p><img src="overview_files/figure-html/unnamed-chunk-2-1.png" width="672"></p>
<p>However, a better way to display these predictions is adding them to the incidence plot using the argument <code>fit</code>:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb19-1" data-line-number="1"><span class="kw">plot</span>(i<span class="fl">.7</span>[<span class="dv">1</span><span class="op">:</span><span class="dv">20</span>], <span class="dt">fit =</span> early.fit)</a></code></pre></div>
<p><img src="overview_files/figure-html/unnamed-chunk-3-1.png" width="672"></p>
<p>In this case, we would ideally like to fit two models, before and after the peak of the epidemic. This is possible using the following approach, if you know what date to use to split the data in two phases:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb20-1" data-line-number="1">fit.both &lt;-<span class="st"> </span><span class="kw"><a href="../reference/fit.html">fit</a></span>(i<span class="fl">.7</span>, <span class="dt">split=</span><span class="kw">as.Date</span>(<span class="st">"2014-10-15"</span>))</a>
<a class="sourceLine" id="cb20-2" data-line-number="2">fit.both</a>
<a class="sourceLine" id="cb20-3" data-line-number="3"><span class="co">#&gt; &lt;list of incidence_fit objects&gt;</span></a>
<a class="sourceLine" id="cb20-4" data-line-number="4"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb20-5" data-line-number="5"><span class="co">#&gt; attr(x, 'locations'): list of vectors with the locations of each incidence_fit object</span></a>
<a class="sourceLine" id="cb20-6" data-line-number="6"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb20-7" data-line-number="7"><span class="co">#&gt; 'before'</span></a>
<a class="sourceLine" id="cb20-8" data-line-number="8"><span class="co">#&gt; 'after'</span></a>
<a class="sourceLine" id="cb20-9" data-line-number="9"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb20-10" data-line-number="10"><span class="co">#&gt; $model: regression of log-incidence over time</span></a>
<a class="sourceLine" id="cb20-11" data-line-number="11"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb20-12" data-line-number="12"><span class="co">#&gt; $info: list containing the following items:</span></a>
<a class="sourceLine" id="cb20-13" data-line-number="13"><span class="co">#&gt;   $r (daily growth rate):</span></a>
<a class="sourceLine" id="cb20-14" data-line-number="14"><span class="co">#&gt;      before       after </span></a>
<a class="sourceLine" id="cb20-15" data-line-number="15"><span class="co">#&gt;  0.02741985 -0.01014465 </span></a>
<a class="sourceLine" id="cb20-16" data-line-number="16"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb20-17" data-line-number="17"><span class="co">#&gt;   $r.conf (confidence interval):</span></a>
<a class="sourceLine" id="cb20-18" data-line-number="18"><span class="co">#&gt;              2.5 %       97.5 %</span></a>
<a class="sourceLine" id="cb20-19" data-line-number="19"><span class="co">#&gt; before  0.02407933  0.030760379</span></a>
<a class="sourceLine" id="cb20-20" data-line-number="20"><span class="co">#&gt; after  -0.01127733 -0.009011981</span></a>
<a class="sourceLine" id="cb20-21" data-line-number="21"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb20-22" data-line-number="22"><span class="co">#&gt;   $doubling (doubling time in days):</span></a>
<a class="sourceLine" id="cb20-23" data-line-number="23"><span class="co">#&gt;   before </span></a>
<a class="sourceLine" id="cb20-24" data-line-number="24"><span class="co">#&gt; 25.27902 </span></a>
<a class="sourceLine" id="cb20-25" data-line-number="25"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb20-26" data-line-number="26"><span class="co">#&gt;   $doubling.conf (confidence interval):</span></a>
<a class="sourceLine" id="cb20-27" data-line-number="27"><span class="co">#&gt;           2.5 %   97.5 %</span></a>
<a class="sourceLine" id="cb20-28" data-line-number="28"><span class="co">#&gt; before 22.53377 28.78598</span></a>
<a class="sourceLine" id="cb20-29" data-line-number="29"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb20-30" data-line-number="30"><span class="co">#&gt;   $halving (halving time in days):</span></a>
<a class="sourceLine" id="cb20-31" data-line-number="31"><span class="co">#&gt;    after </span></a>
<a class="sourceLine" id="cb20-32" data-line-number="32"><span class="co">#&gt; 68.32636 </span></a>
<a class="sourceLine" id="cb20-33" data-line-number="33"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb20-34" data-line-number="34"><span class="co">#&gt;   $halving.conf (confidence interval):</span></a>
<a class="sourceLine" id="cb20-35" data-line-number="35"><span class="co">#&gt;          2.5 %   97.5 %</span></a>
<a class="sourceLine" id="cb20-36" data-line-number="36"><span class="co">#&gt; after 61.46379 76.91397</span></a>
<a class="sourceLine" id="cb20-37" data-line-number="37"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb20-38" data-line-number="38"><span class="co">#&gt;   $pred: data.frame of incidence predictions (56 rows, 6 columns)</span></a>
<a class="sourceLine" id="cb20-39" data-line-number="39"><span class="kw">plot</span>(i<span class="fl">.7</span>, <span class="dt">fit=</span>fit.both)</a></code></pre></div>
<p><img src="overview_files/figure-html/fit.both-1.png" width="672"></p>
<p>This is much better, but the splitting date is not completely optimal. To look for the best possible splitting date (i.e. the one maximizing the average fit of both models), we use:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb21-1" data-line-number="1">best.fit &lt;-<span class="st"> </span><span class="kw"><a href="../reference/fit.html">fit_optim_split</a></span>(i<span class="fl">.7</span>)</a>
<a class="sourceLine" id="cb21-2" data-line-number="2">best.fit</a>
<a class="sourceLine" id="cb21-3" data-line-number="3"><span class="co">#&gt; $df</span></a>
<a class="sourceLine" id="cb21-4" data-line-number="4"><span class="co">#&gt;         dates   mean.R2</span></a>
<a class="sourceLine" id="cb21-5" data-line-number="5"><span class="co">#&gt; 1  2014-08-04 0.7650406</span></a>
<a class="sourceLine" id="cb21-6" data-line-number="6"><span class="co">#&gt; 2  2014-08-11 0.8203351</span></a>
<a class="sourceLine" id="cb21-7" data-line-number="7"><span class="co">#&gt; 3  2014-08-18 0.8598316</span></a>
<a class="sourceLine" id="cb21-8" data-line-number="8"><span class="co">#&gt; 4  2014-08-25 0.8882682</span></a>
<a class="sourceLine" id="cb21-9" data-line-number="9"><span class="co">#&gt; 5  2014-09-01 0.9120857</span></a>
<a class="sourceLine" id="cb21-10" data-line-number="10"><span class="co">#&gt; 6  2014-09-08 0.9246023</span></a>
<a class="sourceLine" id="cb21-11" data-line-number="11"><span class="co">#&gt; 7  2014-09-15 0.9338797</span></a>
<a class="sourceLine" id="cb21-12" data-line-number="12"><span class="co">#&gt; 8  2014-09-22 0.9339813</span></a>
<a class="sourceLine" id="cb21-13" data-line-number="13"><span class="co">#&gt; 9  2014-09-29 0.9333246</span></a>
<a class="sourceLine" id="cb21-14" data-line-number="14"><span class="co">#&gt; 10 2014-10-06 0.9291131</span></a>
<a class="sourceLine" id="cb21-15" data-line-number="15"><span class="co">#&gt; 11 2014-10-13 0.9232523</span></a>
<a class="sourceLine" id="cb21-16" data-line-number="16"><span class="co">#&gt; 12 2014-10-20 0.9160439</span></a>
<a class="sourceLine" id="cb21-17" data-line-number="17"><span class="co">#&gt; 13 2014-10-27 0.9071665</span></a>
<a class="sourceLine" id="cb21-18" data-line-number="18"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb21-19" data-line-number="19"><span class="co">#&gt; $split</span></a>
<a class="sourceLine" id="cb21-20" data-line-number="20"><span class="co">#&gt; [1] "2014-09-22"</span></a>
<a class="sourceLine" id="cb21-21" data-line-number="21"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb21-22" data-line-number="22"><span class="co">#&gt; $fit</span></a>
<a class="sourceLine" id="cb21-23" data-line-number="23"><span class="co">#&gt; &lt;list of incidence_fit objects&gt;</span></a>
<a class="sourceLine" id="cb21-24" data-line-number="24"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb21-25" data-line-number="25"><span class="co">#&gt; attr(x, 'locations'): list of vectors with the locations of each incidence_fit object</span></a>
<a class="sourceLine" id="cb21-26" data-line-number="26"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb21-27" data-line-number="27"><span class="co">#&gt; 'before'</span></a>
<a class="sourceLine" id="cb21-28" data-line-number="28"><span class="co">#&gt; 'after'</span></a>
<a class="sourceLine" id="cb21-29" data-line-number="29"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb21-30" data-line-number="30"><span class="co">#&gt; $model: regression of log-incidence over time</span></a>
<a class="sourceLine" id="cb21-31" data-line-number="31"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb21-32" data-line-number="32"><span class="co">#&gt; $info: list containing the following items:</span></a>
<a class="sourceLine" id="cb21-33" data-line-number="33"><span class="co">#&gt;   $r (daily growth rate):</span></a>
<a class="sourceLine" id="cb21-34" data-line-number="34"><span class="co">#&gt;      before       after </span></a>
<a class="sourceLine" id="cb21-35" data-line-number="35"><span class="co">#&gt;  0.02982209 -0.01016191 </span></a>
<a class="sourceLine" id="cb21-36" data-line-number="36"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb21-37" data-line-number="37"><span class="co">#&gt;   $r.conf (confidence interval):</span></a>
<a class="sourceLine" id="cb21-38" data-line-number="38"><span class="co">#&gt;              2.5 %       97.5 %</span></a>
<a class="sourceLine" id="cb21-39" data-line-number="39"><span class="co">#&gt; before  0.02608945  0.033554736</span></a>
<a class="sourceLine" id="cb21-40" data-line-number="40"><span class="co">#&gt; after  -0.01102526 -0.009298561</span></a>
<a class="sourceLine" id="cb21-41" data-line-number="41"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb21-42" data-line-number="42"><span class="co">#&gt;   $doubling (doubling time in days):</span></a>
<a class="sourceLine" id="cb21-43" data-line-number="43"><span class="co">#&gt;   before </span></a>
<a class="sourceLine" id="cb21-44" data-line-number="44"><span class="co">#&gt; 23.24274 </span></a>
<a class="sourceLine" id="cb21-45" data-line-number="45"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb21-46" data-line-number="46"><span class="co">#&gt;   $doubling.conf (confidence interval):</span></a>
<a class="sourceLine" id="cb21-47" data-line-number="47"><span class="co">#&gt;           2.5 %  97.5 %</span></a>
<a class="sourceLine" id="cb21-48" data-line-number="48"><span class="co">#&gt; before 20.65721 26.5681</span></a>
<a class="sourceLine" id="cb21-49" data-line-number="49"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb21-50" data-line-number="50"><span class="co">#&gt;   $halving (halving time in days):</span></a>
<a class="sourceLine" id="cb21-51" data-line-number="51"><span class="co">#&gt;    after </span></a>
<a class="sourceLine" id="cb21-52" data-line-number="52"><span class="co">#&gt; 68.21031 </span></a>
<a class="sourceLine" id="cb21-53" data-line-number="53"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb21-54" data-line-number="54"><span class="co">#&gt;   $halving.conf (confidence interval):</span></a>
<a class="sourceLine" id="cb21-55" data-line-number="55"><span class="co">#&gt;          2.5 %   97.5 %</span></a>
<a class="sourceLine" id="cb21-56" data-line-number="56"><span class="co">#&gt; after 62.86899 74.54349</span></a>
<a class="sourceLine" id="cb21-57" data-line-number="57"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb21-58" data-line-number="58"><span class="co">#&gt;   $pred: data.frame of incidence predictions (57 rows, 6 columns)</span></a>
<a class="sourceLine" id="cb21-59" data-line-number="59"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb21-60" data-line-number="60"><span class="co">#&gt; $plot</span></a></code></pre></div>
<p><img src="overview_files/figure-html/optim-1.png" width="672"></p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb22-1" data-line-number="1"><span class="kw">plot</span>(i<span class="fl">.7</span>, <span class="dt">fit=</span>best.fit<span class="op">$</span>fit)</a></code></pre></div>
<p><img src="overview_files/figure-html/optim-2.png" width="672"></p>
<p>These models are very good approximation of these data, showing a doubling time of 23.2 days during the first phase, and a halving time of 68.2 days during the second. To access these parameters, you can use the <code><a href="../reference/get_fit.html">get_info()</a></code> function.</p>
<p>The possible parameters are:</p>
<ul>
<li>“r”, the daily growth rate</li>
<li>“doubling” the rate of doubling in days (if “r” is positive)</li>
<li>“halving” the rate of halving in days (if “r” is negative)</li>
<li>“pred” a data frame of incidence predictions</li>
</ul>
<p>For “r”, “doubling”, and “halving”, you can also add “.conf” to get the confidence intervals. Here’s how you can get the doubling and halving times of the above epi curve:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" data-line-number="1"><span class="kw"><a href="../reference/get_fit.html">get_info</a></span>(best.fit<span class="op">$</span>fit, <span class="st">"doubling"</span>)      <span class="co"># doubling time</span></a>
<a class="sourceLine" id="cb23-2" data-line-number="2"><span class="co">#&gt;   before </span></a>
<a class="sourceLine" id="cb23-3" data-line-number="3"><span class="co">#&gt; 23.24274</span></a>
<a class="sourceLine" id="cb23-4" data-line-number="4"><span class="kw"><a href="../reference/get_fit.html">get_info</a></span>(best.fit<span class="op">$</span>fit, <span class="st">"doubling.conf"</span>) <span class="co"># confidence interval</span></a>
<a class="sourceLine" id="cb23-5" data-line-number="5"><span class="co">#&gt;           2.5 %  97.5 %</span></a>
<a class="sourceLine" id="cb23-6" data-line-number="6"><span class="co">#&gt; before 20.65721 26.5681</span></a>
<a class="sourceLine" id="cb23-7" data-line-number="7"><span class="kw"><a href="../reference/get_fit.html">get_info</a></span>(best.fit<span class="op">$</span>fit, <span class="st">"halving"</span>)       </a>
<a class="sourceLine" id="cb23-8" data-line-number="8"><span class="co">#&gt;    after </span></a>
<a class="sourceLine" id="cb23-9" data-line-number="9"><span class="co">#&gt; 68.21031</span></a>
<a class="sourceLine" id="cb23-10" data-line-number="10"><span class="kw"><a href="../reference/get_fit.html">get_info</a></span>(best.fit<span class="op">$</span>fit, <span class="st">"halving.conf"</span>)       </a>
<a class="sourceLine" id="cb23-11" data-line-number="11"><span class="co">#&gt;          2.5 %   97.5 %</span></a>
<a class="sourceLine" id="cb23-12" data-line-number="12"><span class="co">#&gt; after 62.86899 74.54349</span></a></code></pre></div>
<p>Note that <code>fit</code> will also take groups into account if incidence has been computed for several groups:</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb24-1" data-line-number="1">best.fit2 &lt;-<span class="st"> </span><span class="kw"><a href="../reference/fit.html">fit_optim_split</a></span>(i.<span class="fl">7.</span>sex)</a>
<a class="sourceLine" id="cb24-2" data-line-number="2">best.fit2</a>
<a class="sourceLine" id="cb24-3" data-line-number="3"><span class="co">#&gt; $df</span></a>
<a class="sourceLine" id="cb24-4" data-line-number="4"><span class="co">#&gt;         dates   mean.R2 groups</span></a>
<a class="sourceLine" id="cb24-5" data-line-number="5"><span class="co">#&gt; 1  2014-08-04 0.7546016      f</span></a>
<a class="sourceLine" id="cb24-6" data-line-number="6"><span class="co">#&gt; 2  2014-08-11 0.8096672      f</span></a>
<a class="sourceLine" id="cb24-7" data-line-number="7"><span class="co">#&gt; 3  2014-08-18 0.8513743      f</span></a>
<a class="sourceLine" id="cb24-8" data-line-number="8"><span class="co">#&gt; 4  2014-08-25 0.8864424      f</span></a>
<a class="sourceLine" id="cb24-9" data-line-number="9"><span class="co">#&gt; 5  2014-09-01 0.9165063      f</span></a>
<a class="sourceLine" id="cb24-10" data-line-number="10"><span class="co">#&gt; 6  2014-09-08 0.9270248      f</span></a>
<a class="sourceLine" id="cb24-11" data-line-number="11"><span class="co">#&gt; 7  2014-09-15 0.9345352      f</span></a>
<a class="sourceLine" id="cb24-12" data-line-number="12"><span class="co">#&gt; 8  2014-09-22 0.9350323      f</span></a>
<a class="sourceLine" id="cb24-13" data-line-number="13"><span class="co">#&gt; 9  2014-09-29 0.9339121      f</span></a>
<a class="sourceLine" id="cb24-14" data-line-number="14"><span class="co">#&gt; 10 2014-10-06 0.9288956      f</span></a>
<a class="sourceLine" id="cb24-15" data-line-number="15"><span class="co">#&gt; 11 2014-10-13 0.9226037      f</span></a>
<a class="sourceLine" id="cb24-16" data-line-number="16"><span class="co">#&gt; 12 2014-10-20 0.9122727      f</span></a>
<a class="sourceLine" id="cb24-17" data-line-number="17"><span class="co">#&gt; 13 2014-10-27 0.9027890      f</span></a>
<a class="sourceLine" id="cb24-18" data-line-number="18"><span class="co">#&gt; 14 2014-08-04 0.7566712      m</span></a>
<a class="sourceLine" id="cb24-19" data-line-number="19"><span class="co">#&gt; 15 2014-08-11 0.8164693      m</span></a>
<a class="sourceLine" id="cb24-20" data-line-number="20"><span class="co">#&gt; 16 2014-08-18 0.8567850      m</span></a>
<a class="sourceLine" id="cb24-21" data-line-number="21"><span class="co">#&gt; 17 2014-08-25 0.8820669      m</span></a>
<a class="sourceLine" id="cb24-22" data-line-number="22"><span class="co">#&gt; 18 2014-09-01 0.9006668      m</span></a>
<a class="sourceLine" id="cb24-23" data-line-number="23"><span class="co">#&gt; 19 2014-09-08 0.9166004      m</span></a>
<a class="sourceLine" id="cb24-24" data-line-number="24"><span class="co">#&gt; 20 2014-09-15 0.9271862      m</span></a>
<a class="sourceLine" id="cb24-25" data-line-number="25"><span class="co">#&gt; 21 2014-09-22 0.9263339      m</span></a>
<a class="sourceLine" id="cb24-26" data-line-number="26"><span class="co">#&gt; 22 2014-09-29 0.9260695      m</span></a>
<a class="sourceLine" id="cb24-27" data-line-number="27"><span class="co">#&gt; 23 2014-10-06 0.9216350      m</span></a>
<a class="sourceLine" id="cb24-28" data-line-number="28"><span class="co">#&gt; 24 2014-10-13 0.9144120      m</span></a>
<a class="sourceLine" id="cb24-29" data-line-number="29"><span class="co">#&gt; 25 2014-10-20 0.9077086      m</span></a>
<a class="sourceLine" id="cb24-30" data-line-number="30"><span class="co">#&gt; 26 2014-10-27 0.8966333      m</span></a>
<a class="sourceLine" id="cb24-31" data-line-number="31"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb24-32" data-line-number="32"><span class="co">#&gt; $plot</span></a></code></pre></div>
<p><img src="overview_files/figure-html/optim2-1.png" width="672"></p>
<pre><code>#&gt; 
#&gt; $split
#&gt;            f            m 
#&gt; "2014-09-22" "2014-09-15" 
#&gt; 
#&gt; $fit
#&gt; &lt;list of incidence_fit objects&gt;
#&gt; 
#&gt; attr(x, 'locations'): list of vectors with the locations of each incidence_fit object
#&gt; 
#&gt; 'f', 'before'
#&gt; 'm', 'before'
#&gt; 'f', 'after'
#&gt; 'm', 'after'
#&gt; 
#&gt; $model: regression of log-incidence over time
#&gt; 
#&gt; $info: list containing the following items:
#&gt;   $r (daily growth rate):
#&gt;    f_before    m_before     f_after     m_after 
#&gt;  0.02570604  0.02883607 -0.01002297 -0.01038307 
#&gt; 
#&gt;   $r.conf (confidence interval):
#&gt;                2.5 %       97.5 %
#&gt; f_before  0.02289333  0.028518743
#&gt; m_before  0.02502254  0.032649606
#&gt; f_after  -0.01102735 -0.009018595
#&gt; m_after  -0.01138910 -0.009377034
#&gt; 
#&gt;   $doubling (doubling time in days):
#&gt; f_before m_before 
#&gt; 26.96437 24.03750 
#&gt; 
#&gt;   $doubling.conf (confidence interval):
#&gt;             2.5 %   97.5 %
#&gt; f_before 24.30497 30.27725
#&gt; m_before 21.22988 27.70091
#&gt; 
#&gt;   $halving (halving time in days):
#&gt;  f_after  m_after 
#&gt; 69.15586 66.75746 
#&gt; 
#&gt;   $halving.conf (confidence interval):
#&gt;            2.5 %   97.5 %
#&gt; f_after 62.85711 76.85756
#&gt; m_after 60.86059 73.91966
#&gt; 
#&gt;   $pred: data.frame of incidence predictions (111 rows, 7 columns)
plot(i.7.sex, fit=best.fit2$fit)
#&gt; Scale for 'colour' is already present. Adding another scale for
#&gt; 'colour', which will replace the existing scale.
#&gt; Scale for 'colour' is already present. Adding another scale for
#&gt; 'colour', which will replace the existing scale.
#&gt; Scale for 'colour' is already present. Adding another scale for
#&gt; 'colour', which will replace the existing scale.
#&gt; Scale for 'colour' is already present. Adding another scale for
#&gt; 'colour', which will replace the existing scale.</code></pre>
<p><img src="overview_files/figure-html/optim2-2.png" width="672"></p>
<p>Using <code><a href="../reference/get_fit.html">get_info()</a></code> on this fit object will return all groups together:</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb26-1" data-line-number="1"><span class="kw"><a href="../reference/get_fit.html">get_info</a></span>(best.fit2<span class="op">$</span>fit, <span class="st">"doubling"</span>)      <span class="co"># doubling time</span></a>
<a class="sourceLine" id="cb26-2" data-line-number="2"><span class="co">#&gt; f_before m_before </span></a>
<a class="sourceLine" id="cb26-3" data-line-number="3"><span class="co">#&gt; 26.96437 24.03750</span></a>
<a class="sourceLine" id="cb26-4" data-line-number="4"><span class="kw"><a href="../reference/get_fit.html">get_info</a></span>(best.fit2<span class="op">$</span>fit, <span class="st">"doubling.conf"</span>) <span class="co"># confidence interval</span></a>
<a class="sourceLine" id="cb26-5" data-line-number="5"><span class="co">#&gt;             2.5 %   97.5 %</span></a>
<a class="sourceLine" id="cb26-6" data-line-number="6"><span class="co">#&gt; f_before 24.30497 30.27725</span></a>
<a class="sourceLine" id="cb26-7" data-line-number="7"><span class="co">#&gt; m_before 21.22988 27.70091</span></a>
<a class="sourceLine" id="cb26-8" data-line-number="8"><span class="kw"><a href="../reference/get_fit.html">get_info</a></span>(best.fit2<span class="op">$</span>fit, <span class="st">"halving"</span>)       </a>
<a class="sourceLine" id="cb26-9" data-line-number="9"><span class="co">#&gt;  f_after  m_after </span></a>
<a class="sourceLine" id="cb26-10" data-line-number="10"><span class="co">#&gt; 69.15586 66.75746</span></a>
<a class="sourceLine" id="cb26-11" data-line-number="11"><span class="kw"><a href="../reference/get_fit.html">get_info</a></span>(best.fit2<span class="op">$</span>fit, <span class="st">"halving.conf"</span>)       </a>
<a class="sourceLine" id="cb26-12" data-line-number="12"><span class="co">#&gt;            2.5 %   97.5 %</span></a>
<a class="sourceLine" id="cb26-13" data-line-number="13"><span class="co">#&gt; f_after 62.85711 76.85756</span></a>
<a class="sourceLine" id="cb26-14" data-line-number="14"><span class="co">#&gt; m_after 60.86059 73.91966</span></a></code></pre></div>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#installing-the-package">Installing the package</a></li>
      <li><a href="#what-does-it-do">What does it do?</a></li>
      <li>
<a href="#worked-example-simulated-ebola-outbreak">Worked example: simulated Ebola outbreak</a><ul class="nav nav-pills nav-stacked">
<li><a href="#loading-the-data">Loading the data</a></li>
      <li><a href="#computing-and-plotting-incidence">Computing and plotting incidence</a></li>
      <li><a href="#handling-incidence-objects">Handling <code>incidence</code> objects</a></li>
      <li><a href="#modelling-incidence">Modelling incidence</a></li>
      </ul>
</li>
      </ul>
</div>
      </div>

</div>


      <footer><div class="copyright">
  <p>Developed by Thibaut Jombart, Zhian N. Kamvar, Rich FitzJohn.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="http://pkgdown.r-lib.org/">pkgdown</a>.</p>
</div>

      </footer>
</div>

  

  </body>
</html>
