##' Fit exponential models to incidence data
##'
##' This function fits two exponential models to incidence data, of the form:
##' \eqn{log(y)} = r * t + b
##'
##' where 'y' is the incidence, 't' is time (in days), 'r' is the growth rate, and 'b' is the
##' origin.
##'
##' @export
##'
##' @author Thibaut Jombart \email{thibautjombart@@gmail.com}
##'
##' @seealso the \code{\link{incidence}} function to generate the 'incidence' objects.
##'
##' @param x An incidence object, generated by the function \code{\link{incidence}}.
##'
##' @param split An optional time point identifying the separation between the two models. If NULL,
##' a single model is fitted. If provided, two models would be fitted on the time periods on either
##' side of the split.
##'
##' @param level The confidence interval to be used for predictions; defaults to 95\%.
##'
fit <- function(x, split = NULL, level = 0.95){
    if (is.null(split)) {
        lm1 <- lm(log(x$counts) ~ x$dates)
        out <- extract.info(lm1, x$interval, level)
    } else {
        x1 <- x[x$dates <= split]
        x2 <- x[x$dates >= split]
        lm1 <- lm(log(x1$counts) ~ x1$dates)
        lm2 <- lm(log(x2$counts) ~ x2$dates)
        out <- list(model1 = extract.info(lm1, x$interval, level),
                    model2 = extract.info(lm2, x$interval, level))
    }

    out
}





## Non-exported function extracting info and predictions from a lm object

extract.info <- function(reg, interval, level){
    if (is.null(reg)) {
        return(NULL)
    }

    r <- unname(coef(reg)[2])
    r.conf <- confint(reg, 2, level)
    rownames(r.conf) <- NULL

    r.day <- r / interval
    r.day.conf <- r.conf / interval

    pred <- exp(predict(reg))
    pred.conf <- exp(predict(reg, interval = "confidence", level = level))

    info <- list(r = r, r.conf = r.conf,
                r.day = r.day, r.day.conf = r.day.conf,
                pred = pred, pred.conf = pred.conf)

    if (r.day > 0 ) {
        info$doubling <- log(2) / r.day
        info$doubling.conf <- log(2) / r.day.conf
    } else {
        info$halving <- log(0.5) / r.day
        info$halving.conf <- log(0.5) / r.day.conf
    }

    out <- list(lm = reg, info = info)
    class(out) <- "incidence.fit"
    out
}
