##' Plot function for incidence objects
##'
##' This function is used to visualise the output of the \code{\link{incidence}} function, using the
##' package \code{ggplot2}.
##'
##'
##' @export
##'
##' @importFrom graphics plot
##'
##' @author Thibaut Jombart \email{thibautjombart@@gmail.com}
##'
##' @seealso the \code{\link{incidence}} function to generate the 'incidence' objects.
##'
##' @param x An incidence object, generated by the function \code{\link{incidence}}.
##'
##' @param ... Further arguments passed to other methods (currently not used).
##'
##' @param fit An 'incidence_fit' objet as returned by \code{\link{fit}}.
##'
##' @param stack A logical indicating if bars of multiple groups should be stacked, or displayed
##' side-by-side.
##'
##' @param border The color to be used for the borders of the bars; NA for invisiable borders.
##'
##' @param col.pal The color palette to be used for the groups; defaults to \code{pal1}. See
##' \code{\link{pal1}} for other palettes implemented in incidence.
##'
##' @param alpha The alpha level for color transparency, with 1 being fully opaque and 0 fully
##' transparent; defaults to 0.8.
##'
##' @param xlab The label to be used for the x-axis; empty by default.
##'
##' @param ylab The label to be used for the y-axis; by default, a label will be generated
##' automatically according to the time interval used in incidence computation.
##'
##' @examples
##'
##' if(require(outbreaks)) {
##'   onset <- ebola.sim$linelist$date.of.onset
##'
##'   ## daily incidence
##'   inc <- incidence(onset)
##'   inc
##'   plot(inc)
##'
##'   ## weekly incidence
##'   inc.week <- incidence(onset, interval = 7)
##'   inc.week
##'   plot(inc.week)
##'   plot(inc.week, border = "white") # with visible border
##'
##'   ## use group information
##'   sex <- ebola.sim$linelist$gender
##'   inc.week.gender <- incidence(onset, interval = 7, groups = sex)
##'   plot(inc.week.gender, stack = TRUE)
##'
##'   ## adding fit
##'   fit <- fit_optim_split(inc.week.gender)$fit
##'   plot(inc.week.gender, fit = fit)
##' }
##'
plot.incidence <- function(x, ..., fit = NULL, stack = FALSE,
                           border = NA, col.pal = pal1, alpha = .8,
                           xlab = "", ylab = NULL) {

    ## extract data in suitable format for ggplot2
    df <- as.data.frame(x, long=TRUE)
    n.groups <- ncol(x$counts)


    ## Use custom labels for usual time intervals
    if (is.null(ylab)) {
        if (x$interval == 1) {
            ylab <- "Daily incidence"
        } else if (x$interval == 7) {
            ylab <- "Weekly incidence"
        } else if (x$interval == 14) {
            ylab <- "Biweekly incidence"
        } else {
            ylab <- sprintf("Incidence by period of %d days", x$interval)
        }
    }

    ## Handle stacking
    stack.txt <- ifelse(stack, "stack", "dodge")

    ## By default, the annotation of bars in geom_bar puts the label in the middle of the bar. This
    ## is wrong in our case as the annotation of a time interval is the lower (left) bound, and
    ## should therefore be left-aligned with the bar. Note that we cannot use position_nudge to
    ## create the x-offset as we need the 'position' argument for stacking. Best option here is add
    ## x$interval / 2 to the x-axis.

    x.axis.txt <- paste("dates", x$interval/2, sep = "+")

    out <- ggplot2::ggplot(df, ggplot2::aes_string(x = x.axis.txt, y = "counts")) +
        ggplot2::geom_bar(stat="identity", width = x$interval,
                          position = stack.txt, color = border, alpha = alpha) +
            ggplot2::labs(x = xlab, y = ylab)


    ## Handle fit objects here; 'fit' can be either an 'incidence_fit' object, or a list of
    ## these. In the case of a list, we add geoms one after the other.

    if (!is.null(fit)) {
        if (inherits(fit, "incidence_fit")) {
            out <- add_incidence_fit(out, fit)
        } else if (is.list(fit)) {
            for (i in seq_along(fit)) {
                fit.i <- fit[[i]]
                if (!inherits(fit.i, "incidence_fit")) {
                    stop(sprintf("The %d-th item in 'fit' is not an 'incidence_fit' object, but a %s",
                                 i, class(fit.i)))
                }
                out <- add_incidence_fit(out, fit.i)
            }
        } else {
            stop("fit must be a 'incidence_fit' object, or a list of these")
        }
    }

    ## Add color to groups if needed
    if (ncol(df) > 2) {
        out <- out + ggplot2::aes_string(fill = "groups") +
            ggplot2::scale_fill_manual(values = col.pal(n.groups))
        if (!is.null(fit)) {
            out <- out + ggplot2::aes_string(color = "groups") +
            ggplot2::scale_color_manual(values = col.pal(n.groups))
        }
    }

    out
}




## ##' @export
## plot.incidence_summary <- function(x, ..., ylab = NULL) {
##   if (is.null(ylab)) {
##     ylab <- sprintf("Cases (%d day %s)", x$interval,
##                     if (x$rolling) "rolling average" else "total")
##   }
##   plot.incidence(x, ..., ylab = ylab)
## }
